### ISSUE TITLE
Removing space-pen

### ISSUE THREAD

**Issue by zertosh** [suda/tool-bar#135]
I was about to start removing space-pen in favor of using the DOM directly, but then I figured I'd ask first if it made sense to do a port of the current code to ES6 and then remove space-pen. If that sounds good, do you have a preference on lint rules?

**Comment by jerone** [comment]
That would be so cool! It's on my own todo list for a few months now, since I saw the trend happening where other packages also switched to ES6. Combining that with removing the `space-pen` dependency would be great too, as it looks like the Atom team is deprecating that library in the near future and building [their own](https://github.com/atom/etch). For me I don't have a clear preference for ES6 linting as I've not done much. I've used `eslint-config-standard` at one of [my projects](https://github.com/jerone/atom-html2js/blob/master/package.json#L28-L29), but if you've got a better preference go for it.

**:+1: on removing `space-pen`.
:+1: on switching to ES6.**

With one remark that we don't lose any API functionality and the tests are also converted!
I can even chip in if you want.

I do think that we need @suda's permission as well!

**Comment by suda** [comment]
I'm not a fan directly manipulating DOM like it's 1997 😄  But I would love if we could switch to Etch. I hope Atom team won't introduce too many breaking changes in. So in summary:

:+1: on removing `space-pen`
:+1: on switching to ES6
:+1: on using Etch

**Comment by jerone** [comment]
> I'm not a fan directly manipulating DOM like it's 1997

Remember that we are working in an Chromium environment, so we can always use the latest and best API's available. jQuery isn't required here anymore.



> But I would love if we could switch to Etch

I asked on Slack about Etch and it's state. The answer was in the direction of it still being developed and API's may change. On the other side they sound confident that the direction it's headed is the right one. Just don't want to make promises. They are using it on some Atom stuff so I don't foresee it going away. It looked like they were interested in more feedback while implementing it into existing packages.

This creates the question if we should jump on it right now, or wait a little bit more until it's more mature...

**Comment by jerone** [comment]
So now #136 is merged let's discuss how `space-pen` can be removed...

I'm kinda hesitated to introduce another framework, that's not even released yet and might be a bit overkill for this package. On the otherhand I might be cool if we were the first mayor package introducing Etch framework.

@BinaryMuse Do you have a opinion if the tool-bar package is a good starting point to implement Etch?

**Comment by BinaryMuse** [comment]
@jerone I'm not massively familiar with tool-bar, but I've been using Etch a lot recently (some personal projects, and some apps for Electron talks this year) and I have to say I'm pretty happy with it overall. I'm trying to be very conservative with making any sort of promises but at this point I *personally* believe there would have to be a very real strategic reason for us not to use it interally. It has a pretty small surface area and seems to work really well, so if it were me I'd say go for it!

**Comment by zertosh** [comment]
@jerone I don't think that `tool-bar` needs any framework for the little bit of DOM that it touches. I can put something together in the next couple of days.

**Comment by jerone** [comment]
Let's see how much overhead we get by going with native DOM?

**Comment by jerone** [comment]
By the awesome work of @zertosh this issue can be closed!
