### ISSUE TITLE
Toolbar not visible on Atom 1.19

### ISSUE THREAD

**Issue by 16patsle** [suda/tool-bar#202]
### Description

After updating to the newly released Atom 1.19, the toolbar added by this package is no longer visible. The position seems to have no effect. If you toggle the toolbar on and off, you will notice the editor is shifted by a couple pixels. This is the only (somewhat) visible sign of the toolbar.

### Steps to Reproduce

1. Use/update to Atom 1.19
2. Have the toolbar activated
3. Notice the lack of toolbar
4. Toggle the toolbar off in settings
5. Notice how the editor shifts to fill the couple of pixels the toolbar used

**Expected behavior:** Visible toolbar

**Actual behavior:** Toolbar not visible (only a couple of pixels wide)

**Reproduces how often:** Seems to reproduce all the time

### Versions
Atom: 1.19.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
OS: macOS Sierra 10.12.6

### Additional Information

```
Community Packages (30)
├── atom-beautify@0.30.4
├── atom-clock@0.1.13
├── atom-ternjs@0.18.3
├── busy-signal@1.4.3
├── caniuse@0.9.2
├── docblockr@0.11.0
├── editor-stats@0.17.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.10
├── flex-tool-bar@0.12.0
├── intentions@1.1.5
├── language-apache@1.7.0
├── language-gitignore@0.3.0
├── language-markdown@0.25.1
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-stylelint@4.0.1
├── linter-ui-default@1.6.3
├── minimap@4.29.3
├── minimap-linter@2.0.2
├── minimap-pigments@0.2.2
├── pigments@0.40.1
├── project-manager@3.3.5
├── riot-tag@1.1.1
├── termination@0.5.1
├── todo-show@1.11.0
└── tool-bar@1.1.0
```

**Comment by marcusguttenplan** [comment]
Seconding this, Atom updated in the background at some point today and the toolbar disappeared.

Digging around dev tools, the `.tool-bar` div isn't getting a height or width, setting it manually brings the toolbar back -- but without any icons. It seems like the plugins from the config file are no longer being added to the toolbar, or their divs aren't being created.

Looking through Atom's changelog, can't find anything that stands out as a root cause of the issue. Also don't see anything in the `tool-bar` codebase like `addItem` that could be a cause.

Any ideas, point me in the right direction and I can submit a PR!

**Comment by 16patsle** [comment]
It could well be caused by some tool-bar plugin (i.e. I am using flex-tool-bar too). Maybe I find out more later

**Comment by marcusguttenplan** [comment]
Thought that might be a good lead because I am also using flex-tool-bar, but disabling that and working through dev tools still doesn't find a solution. `tool-bar` itself still uses a lot of flexbox, and disabling the flex properties and playing with display: block and visibility: visible doesn't lead anywhere.

In 1.19, Atom has changed their approach the DOM, so it's possible that the plugins from the config aren't being given classes and appended correctly because of something in [this PR](https://github.com/atom/atom/pull/13880).

If you see anything that looks suspect, please point it out! I've only played with electron and react in passing, and debugging Atom packages is a bit of a hassle. In the meantime, I've downgraded to 1.18 by downloading from source, and blocking its network call to atom.io to prevent updating. It runs alongside 1.19 and uses all existing packages, so it's not too much trouble. I also tried upgrading to 1.20 beta, but problem persists.

Tool-bar is the greatest part of atom, and more than willing to submit a PR if a fix can be found.

**Comment by marcusguttenplan** [comment]
Also just noticed [this PR](https://github.com/atom/atom/pull/12696) about the updated electron breaking icons and fonts, could possibly just be that the icons that `tool-bar` uses aren't being rendered at all, leaving the tool-bar div empty

**Comment by 16patsle** [comment]
I might have found the solution. I noticed there was a yellow/orange icon in the Atom status bar, which took me to a page listing incompatible packages. The error supposedly was to do with some native modules that was incompatible. Clicking the Rebuild button worked for me at least (although a number of other packages seem to have other issues with Atom 1.18).

Seemed like the issue was with the flex-tool-bar package. If I remember, I will create an issue over there tomorrow (a bit to late to do it now). The termination package supposedly had the same issue by the way.

**Comment by marcusguttenplan** [comment]
Good call! That solution works!

There is an [open issue](https://github.com/cakecatz/flex-toolbar/issues/112) over there already. Rebuilding totally works, but only if done via the UI! I tried to rebuild via apm first, with no luck.

**Comment by 16patsle** [comment]
Great! That probably means I should close this issue, as the error is confirmed to not be in this package.
