### ISSUE TITLE
Some icons have disappeared with tool bar 1.2.0

### ISSUE THREAD

**Issue by Silverfox28** [suda/tool-bar#268]
The "Run All", "Stop Julia", "Interrupt Julia" and "Start Remote Julia Process" icons have disappeared since the last update (v 1.2.0)

**Comment by BoundaryValueProblems** [comment]
I have exactly the same issue, but this problem already started at v1.1.13. So, I wished v1.2.0 fixed this icon problem, but it didn't... I hope that the next version will fix this.

**Comment by suda** [comment]
Hi there! We updated the Ionicons set that renamed their icons to allow two variants: iOS and Material style which [caused the old icons to diseappear](https://github.com/suda/tool-bar/issues/264). This is why this change was re-released as 1.2.0 due to the breaking change.
The best way to fix this issue, is to change the icon names to contain the `ios-` or `md-` prefix.

**Comment by Silverfox28** [comment]
Ok. I did what was proposed, but the "Stop Julia" icon is still not visible!

**Comment by ericcornelissen** [comment]
@Silverfox28 can you share your configuration file and/or what package you're using for Julia? That would allow us to figure out why it is missing and how to fix it. Alternatively you can see if you can find the icon you want [on the ionicons website](https://ionicons.com/) and figure out the name you need that way.

**Comment by Silverfox28** [comment]
[ionicons.zip](https://github.com/suda/tool-bar/files/3691000/ionicons.zip)

**Comment by Silverfox28** [comment]
I solved
![Screenshot](https://user-images.githubusercontent.com/7389330/66218964-8c1cf100-e6ca-11e9-9d74-342affc35e84.png)
