### ISSUE TITLE
no default icon

### ISSUE THREAD

**Issue by arrow974** [suda/tool-bar#270]
Since 1.2.0, icons for Open file, open folder, save, fold all,unfold all and toggle command palette disappear even spaces exists.
I try plugin as tool-bar-main and tool-bar-atom but same behavior.

Thanks

**Comment by Spaceship-Serenity** [comment]
I've experienced the same issue, both in windows 10 and macOS. The buttons exist and are functional but the icons are gone. I have the markdown plugin installed and those icons are visible.
<img width="679" alt="Screen Shot 2019-10-24 at 1 01 32 AM" src="https://user-images.githubusercontent.com/55212540/67454890-d4f50500-f5f9-11e9-96ba-0bb00381be30.png">

**Comment by suda** [comment]
This is caused by [updating ionicons](https://github.com/suda/tool-bar/issues/268#issuecomment-538027667). The packages that provide the tool bar buttons (like [`tool-bar-main`](https://github.com/suda/tool-bar-main) or [`tool-bar-atom`](https://github.com/jeselxe/tool-bar-atom)) have to be updated.

I already [fixed the `tool-bar-main`](https://github.com/suda/tool-bar-main/pull/20) but please report this to other package creators if you notice the issue.
