### ISSUE TITLE
`ion` icons now showing any longer

### ISSUE THREAD

**Issue by gilbertohasnofb** [suda/tool-bar#275]
I noticed today that all the icons from the `ion` icon set are not showing up in my custom made tool bar. Can anyone reproduce the issue with other tool bars?

**Comment by ericcornelissen** [comment]
Seems to be the same as #264, #266, #268, #269, it's caused by an update to the font (in #263). Try prefixing them with `md-` or `ios-`. Some icons may also have been removed (not sure about that), anyway you can have a look at [the Ionicons website](https://ionicons.com/) to find the right names for the icons.

Hope that helps :slightly_smiling_face:

**Comment by gilbertohasnofb** [comment]
@ericcornelissen Thank you so much, it does help. It turns out all icons from `ion` must now be prefaced by either `md-` or `ios-`, and a lot of them have been removed or renamed. It's just a bit confusing because searching for an icon on their website using `md-` or `ios-` does not match anything.
